# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9190
  servlet:
    context-path: /
# 日志配置
logging:
  level:
    root: info
    io.renren: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
  file: logs\renren-client-simple.log
# mysql
spring:
  application:
    name: renren-client-simple
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8100/eureka


    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
