# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 1999
  servlet:
    context-path: /
# 日志配置
logging:
  level:
    root: info
    io.renren: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
  file: renren-client-test1.log
# mysql
spring:
  application:
    name: renren-client-test1

